name: Release

on:
  workflow_dispatch:
    inputs:
      VersionPrefix:
        type: string
        description: The version of the library
        required: true
        default: 0.9.0
      VersionSuffix:
        type: string
        description: The version suffix of the library (for example rc.1)

run-name: ${{ inputs.VersionPrefix }}-${{ inputs.VersionSuffix }}

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET 8.x
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'
      
      - name: Build
        run: dotnet pack 
          --property:Configuration=Release
          --property:VersionPrefix=${{ github.event.inputs.VersionPrefix }}
          --property:VersionSuffix=${{ github.event.inputs.VersionSuffix }}
          "src/Pdf.PasswordRemover.WinForms/Pdf.PasswordRemover.WinForms.Setup.vdproj"