name: Release

on:
  workflow_dispatch:
    inputs:
      VersionPrefix:
        type: string
        description: The version of the library
        required: true
        default: 0.9.0
      VersionSuffix:
        type: string
        description: The version suffix of the library (for example rc.1)

run-name: ${{ inputs.VersionPrefix }}-${{ inputs.VersionSuffix }}

jobs:
  build:
    env:
      SETUP_PROJECT_FILE: "./src/Pdf.PasswordRemover.WinForms.Setup/Pdf.PasswordRemover.WinForms.Setup.vdproj"
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET 8.x
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build
        run: dotnet build --property:Configuration=Release --property:AssemblyVersion=${{ inputs.VersionPrefix }} --property:FileVersion=${{ inputs.VersionPrefix }} --property:AssemblyInformationalVersion=${{ inputs.VersionPrefix }}-${{ inputs.VersionSuffix }} "./src/Pdf.PasswordRemover.WinForms/Pdf.PasswordRemover.WinForms.csproj"

      - name: Setup VS Dev Environment
        uses: seanmiddleditch/gha-setup-vsdevenv@v4

      - name: Update .vdproj version and output file name
        shell: pwsh
        run: |
          $newProductCode = [System.Guid]::NewGuid().ToString("B").ToUpper()
          $content = Get-Content -Path $env:SETUP_PROJECT_FILE -Raw

          $content = $content -replace '"ProductVersion" = "8:.*?"', '"ProductVersion" = "8:${{ inputs.VersionPrefix }}"'
          $content = $content -replace '"OutputFilename" = "8:Release\\\\PdfPasswordRemover.msi"', '"OutputFilename" = "8:Release\\PdfPasswordRemover_${{ inputs.VersionPrefix }}-${{ inputs.VersionSuffix }}.msi"'
          $content = $content -replace '"ProductCode" = "8:{CB215E38-E864-48E0-851B-6B2B67958B42}"', ('"ProductCode" = "8:' + $newProductCode + '"')

          Set-Content -Path $env:SETUP_PROJECT_FILE -Value $content

          Write-Host "Version updated to '${{ inputs.VersionPrefix }}' in '$env:SETUP_PROJECT_FILE'"
          Write-Host "OutputFilename property updated to 'Release\\PdfPasswordRemover_${{ inputs.VersionPrefix }}-${{ inputs.VersionSuffix }}.msi' in '$env:SETUP_PROJECT_FILE'"
          Write-Host "ProductCode property updated to '$newProductCode' in '$env:SETUP_PROJECT_FILE'"
      
      - name: Build
        run: devenv "${{ env.SETUP_PROJECT_FILE }}" /Build "Release"

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: installer
          path: |
            ./src/Pdf.PasswordRemover.WinForms.Setup/Release/